name: Build and Deploy WASM32 Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Trunk
      run: |
        cargo install --locked trunk

    - name: Build
      run: |
        git submodule update --remote
        trunk build --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.CPULIB_GH_PAGES_TOKEN }}
        publish_dir: ./dist
